### ISSUE TITLE
We are ready to go.

### ISSUE THREAD

**Issue by x13a** [x13a/zig-scrypt#1]
Hello @jedisct1 . Suppose library is ready. I implemented basic [phc-string](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md) parser to encode / decode kdf. It can be used with future argon2 and with current kdf(s) as well. Plus removed all comptime and accept allocator to not expose stack.

**Comment by jedisct1** [comment]
Awesome work!

For leveraging the existing Salsa code, round-reduced versions need to be available. A PR was made to bring this to ChaCha, and doing the same to Salsa and exposing the core functions the same way we expose AES will be trivial. 

But the scrypt code can be merged with its current implementation of Salsa, and updated later.

**Comment by jedisct1** [comment]
The PHC string parser is great to have, and will indeed be useful for Argon2!

But besides `passlib`, looks like nothing is using the PHC format with scrypt yet. [This](https://gitlab.com/jas/scrypt-unix-crypt/blob/master/unix-scrypt.txt) is the most common format.

**Comment by jedisct1** [comment]
The code looks really too much like Go code.

Zig has (fixed-length) arrays, you should take advantage of these :)

Do you mind if I try to make this code more idiomatic?

**Comment by x13a** [comment]
> This is the most common format.
It seems that it is old style crypt format named `mcf`. No problem here, I will implement encoder / decoder for this too.

> Do you mind if I try to make this code more idiomatic?
Of cause, you are crypto sensei :)

**Comment by x13a** [comment]
> This is the most common format.

It seems that it is old style crypt format named `mcf`. No problem here, I will implement encoder / decoder for this too.

> Do you mind if I try to make this code more idiomatic?

Of cause, you are crypto sensei :)

**Comment by jedisct1** [comment]
Hi!

> It seems that it is old style crypt format named mcf. No problem here, I will implement encoder / decoder for this too.

Don't worry about it, I have a PR almost ready for that :)
